### ISSUE TITLE
Confluent CLI install tool broken

### ISSUE THREAD

**Issue by paulseghers** [dfds/tika#49]
The confluent install tool was updated and returns a 404 for any version `<v2.17.1`.
We found this while trying to run a test build of an image using [this](https://github.com/dfds/tika/blob/master/server/Dockerfile) Dockerfile. Line 29 fails:
 ```RUN curl -sL --http1.1 https://cnfl.io/cli | sh -s -- -b /usr/local/bin $CONFLUENT_CLI_VERSION```
because version `"v2.12.0" ` is hardcoded in the Docker build context. <br><br>Running it with `latest` or hard-coding newer versions works, but parts in the rest of tika likely need to be re-written to work with other versions.

**Comment by paulseghers** [comment]
Found while working on [#802](https://github.com/dfds/cloudplatform/issues/802) from SA work. We'll be skipping tika on this one

**Comment by paulseghers** [comment]
@SEQUOIIA @wcarlsen, tagging you guys so you can properly tag this (I don't have the right write rights) before it gets forgotten and resurfaces when something breaks

**Comment by SEQUOIIA** [comment]
Fixed. Thanks!
